"use client";
import type{FormEvent}from"react";import{useState}from"react";import{useRouter}from"next/navigation";

import type{CreatorProfileRow,CreatorReadiness,CreatorTaxonomyRelations}from"@/server/creator/creator-service";import type{CreatorAttachableMediaRow}from"@/server/creator/creator-media-service";import type{SocialProfileRow}from"@/server/creator/social-profile-service";import type{ReferenceDataBundle}from"@/server/reference-data/reference-data-service";import type{TaxonomyDefinitionRow}from"@/server/taxonomy/taxonomy-service";
type Profile=Pick<CreatorProfileRow,"id"|"display_name"|"bio"|"country_code"|"language_code"|"timezone_code"|"region"|"city"|"status"|"marketplace_visibility"|"availability"|"avatar_media_asset_id">|null;
type Taxonomy=TaxonomyDefinitionRow;
type Social=SocialProfileRow;
const statusLabels:Record<string,string>={DRAFT:"Rascunho",UNDER_REVIEW:"Em análise",ACTIVE:"Ativo",LIMITED:"Limitado",SUSPENDED:"Suspenso",DISABLED:"Desativado"};
const availabilityLabels:Record<string,string>={AVAILABLE:"Disponível",LIMITED_AVAILABILITY:"Disponibilidade limitada",UNAVAILABLE:"Indisponível"};
const visibilityLabels:Record<string,string>={VISIBLE:"Visível",HIDDEN:"Oculto"};
const platformLabels:Record<string,string>={TIKTOK:"TikTok",INSTAGRAM:"Instagram",YOUTUBE:"YouTube"};
const readinessLabels:Record<string,string>={MISSING_DISPLAY_NAME:"Nome de exibição",MISSING_COUNTRY:"País",MISSING_LANGUAGE:"Idioma principal",MISSING_NICHE:"Nicho",MISSING_SOCIAL_PROFILE:"Rede social",EMAIL_VERIFICATION_REQUIRED:"Verificação de e-mail"};

async function api(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}});const payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message??"Não foi possível concluir a operação.");return payload;}

export function CreatorPanel({profile,taxonomies,referenceData,relations,socials,readiness,attachableMedia}:{profile:Profile;taxonomies:Taxonomy[];referenceData:ReferenceDataBundle;relations:CreatorTaxonomyRelations;socials:Social[];readiness:CreatorReadiness|null;attachableMedia:CreatorAttachableMediaRow[]}){
const router=useRouter();const[message,setMessage]=useState("");const taxonomy=(code:string)=>taxonomies.find(t=>t.code===code)?.values.filter(v=>v.status==="ACTIVE")??[];
async function submitJson(url:string,body:unknown,success:string){try{await api(url,{method:"POST",body:JSON.stringify(body)});setMessage(success);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível concluir a operação.");}}
async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const d=new FormData(f);const body={displayName:String(d.get("displayName")??""),bio:String(d.get("bio")??"")||null,countryCode:String(d.get("countryCode")??""),languageCode:String(d.get("languageCode")??""),timezoneCode:String(d.get("timezoneCode")??""),region:String(d.get("region")??"")||null,city:String(d.get("city")??"")||null};try{await api("/api/creator",{method:profile?"PUT":"POST",body:JSON.stringify(profile?{creatorProfileId:profile.id,...body}:body)});setMessage(profile?"Perfil atualizado.":"Perfil de Creator criado.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar o perfil.");}}
async function addTaxonomy(kind:"NICHE"|"CONTENT_STYLE"|"MUSIC_GENRE",id:string){if(!profile||!id)return;await submitJson("/api/creator/taxonomy",{creatorProfileId:profile.id,taxonomyValueId:id,kind,primary:kind==="NICHE"&&relations.niches.length===0},"Classificação adicionada.");}
async function addSocial(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;const f=e.currentTarget;const d=new FormData(f);try{await api("/api/creator/social",{method:"POST",body:JSON.stringify({creatorProfileId:profile.id,platform:String(d.get("platform")),handle:String(d.get("handle")),profileUrl:String(d.get("profileUrl"))||null})});setMessage("Rede social adicionada.");f.reset();router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível adicionar a rede social.");}}
return <div className="module-surface creator-shell"><header className="page-header"><div><p className="eyebrow">CREATORS</p><h1>Perfil de Creator</h1><p>Seu perfil profissional para futuras oportunidades de Creator Marketing.</p></div></header>{message?<p className="notice" role="status">{message}</p>:null}
<section className="creator-grid"><article className="card creator-span"><div className="section-heading"><div><p className="eyebrow">PERFIL</p><h2>{profile?"Dados do Creator":"Criar perfil de Creator"}</h2></div>{profile?<div className="status-pills"><span>{statusLabels[profile.status]??profile.status}</span><span>{availabilityLabels[profile.availability]??profile.availability}</span><span>{visibilityLabels[profile.marketplace_visibility]??profile.marketplace_visibility}</span></div>:null}</div>
<form className="form two-column-form" onSubmit={saveProfile}><label>Nome de exibição<input name="displayName" required minLength={2} maxLength={120} defaultValue={profile?.display_name??""}/></label><label>País<select name="countryCode" required defaultValue={profile?.country_code??"BR"}>{referenceData.countries.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Idioma principal<select name="languageCode" required defaultValue={profile?.language_code??"pt-BR"}>{referenceData.languages.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Fuso horário<select name="timezoneCode" required defaultValue={profile?.timezone_code??"America/Sao_Paulo"}>{referenceData.timezones.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Estado/região<input name="region" maxLength={120} defaultValue={profile?.region??""}/></label><label>Cidade<input name="city" maxLength={120} defaultValue={profile?.city??""}/></label><label className="full-field">Bio<textarea name="bio" maxLength={1200} rows={4} defaultValue={profile?.bio??""}/></label><button type="submit">{profile?"Salvar alterações":"Criar perfil"}</button></form></article>
{profile?<><article className="card"><p className="eyebrow">PRONTIDÃO</p><h2>Prontidão do perfil</h2>{readiness?.technicalReady?<p className="success-copy">Perfil tecnicamente pronto para análise.</p>:<><p>Complete os itens antes de enviar para análise:</p><ul>{readiness?.missing.map(code=><li key={code}>{readinessLabels[code]??"Requisito pendente"}</li>)}</ul></>}<p className="helper">Termos de Creator: etapa legal futura ainda não implementada.</p><button type="button" disabled={!readiness?.technicalReady||profile.status==="UNDER_REVIEW"} onClick={()=>void submitJson("/api/creator/submit",{creatorProfileId:profile.id},"Perfil enviado para análise.")}>Enviar para análise</button></article>
<article className="card"><p className="eyebrow">CLASSIFICAÇÃO</p><h2>Nichos e estilos</h2><p><strong>Nichos:</strong> {relations.niches.map(x=>x.label).join(", ")||"Nenhum"}</p><select aria-label="Adicionar nicho" defaultValue="" onChange={e=>{void addTaxonomy("NICHE",e.target.value);e.currentTarget.value="";}}><option value="" disabled>Adicionar nicho</option>{taxonomy("CREATOR_NICHE").map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><p><strong>Estilos de conteúdo:</strong> {relations.contentStyles.map(x=>x.label).join(", ")||"Nenhum"}</p><select aria-label="Adicionar estilo de conteúdo" defaultValue="" onChange={e=>{void addTaxonomy("CONTENT_STYLE",e.target.value);e.currentTarget.value="";}}><option value="" disabled>Adicionar estilo</option>{taxonomy("CONTENT_STYLE").map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><p><strong>Preferências musicais:</strong> {relations.musicGenres.map(x=>x.label).join(", ")||"Nenhuma"}</p><select aria-label="Adicionar preferência musical" defaultValue="" onChange={e=>{void addTaxonomy("MUSIC_GENRE",e.target.value);e.currentTarget.value="";}}><option value="" disabled>Adicionar gênero</option>{taxonomy("MUSIC_GENRE").map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></article>
<article className="card"><p className="eyebrow">REDES SOCIAIS</p><h2>Perfis declarados</h2>{socials.length===0?<p>Nenhuma rede social adicionada.</p>:<div className="stack">{socials.map(s=><div className="social-row" key={s.id}><div><strong>{platformLabels[s.platform]??s.platform} · {s.handle.startsWith("@")?s.handle:`@${s.handle}`}</strong><span>Declarado manualmente · não conectado ao provedor</span>{s.captured_at?<small>Métricas declaradas em {new Date(s.captured_at).toLocaleDateString("pt-BR")}: {s.followers??"—"} seguidores</small>:null}</div></div>)}</div>}<form className="form" onSubmit={addSocial}><label>Plataforma<select name="platform" defaultValue="INSTAGRAM"><option value="INSTAGRAM">Instagram</option><option value="TIKTOK">TikTok</option><option value="YOUTUBE">YouTube</option></select></label><label>Usuário/handle<input name="handle" required placeholder="@seuperfil"/></label><label>URL HTTPS<input name="profileUrl" type="url" placeholder="https://instagram.com/seuperfil"/></label><button type="submit">Adicionar rede social</button></form></article>
<article className="card"><p className="eyebrow">DISPONIBILIDADE</p><h2>Disponibilidade e visibilidade</h2><label>Disponibilidade<select value={profile.availability} onChange={e=>void submitJson("/api/creator/availability",{creatorProfileId:profile.id,availability:e.target.value},"Disponibilidade atualizada.")}><option value="AVAILABLE">Disponível</option><option value="LIMITED_AVAILABILITY">Disponibilidade limitada</option><option value="UNAVAILABLE">Indisponível</option></select></label><p className="helper">Indisponível não desativa seu perfil; apenas sinaliza futuras oportunidades.</p><label>Visibilidade<select value={profile.marketplace_visibility} disabled={profile.status!=="ACTIVE"} onChange={e=>void submitJson("/api/creator/visibility",{creatorProfileId:profile.id,visibility:e.target.value},"Visibilidade atualizada.")}><option value="HIDDEN">Oculto</option><option value="VISIBLE">Visível</option></select></label><p className="helper">A visibilidade pública só poderá ser ativada após aprovação do perfil.</p></article>
<article className="card"><p className="eyebrow">MÍDIA</p><h2>Avatar</h2>{attachableMedia.length===0?<p>Nenhuma mídia própria elegível encontrada nos workspaces aos quais você tem acesso.</p>:<label>Arquivo<select defaultValue={profile.avatar_media_asset_id??""} onChange={e=>void submitJson("/api/creator/avatar",{creatorProfileId:profile.id,mediaAssetId:e.target.value||null},"Avatar atualizado.")}><option value="">Sem avatar</option>{attachableMedia.filter(x=>x.media_kind==="IMAGE").map(x=><option key={x.id} value={x.id}>{x.original_file_name}</option>)}</select></label>}<p className="helper">O Creator reutiliza a fundação de Mídia Compartilhada; nenhum storage paralelo é criado.</p></article></>:null}</section></div>;
}
