"use client";
import type { FormEvent } from "react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { MediaAssetView } from "@/server/media/media-service";
import type { ArtistView } from "@/server/music-catalog/artist-service";
import type { CatalogListing, CatalogTrackRow } from "@/server/music-catalog/catalog-service";
import type { ReferenceDataBundle } from "@/server/reference-data/reference-data-service";
import type { TaxonomyDefinitionRow } from "@/server/taxonomy/taxonomy-service";

type Artist=ArtistView;
type Track=CatalogTrackRow;
type Taxonomy=TaxonomyDefinitionRow;
type Media=Pick<MediaAssetView,"id"|"originalFileName"|"mediaKind"|"status">;
type ImportArtist={name:string;normalizedName:string;kind:string;artistId?:string;candidates?:{id:string;artisticName:string}[]};
type ImportRow={id:string;row_number:number;classification:string;normalized_data:{trackTitle:string;releaseTitle:string;releaseType:string;trackNumber:number;primaryArtists:ImportArtist[];featuredArtists:ImportArtist[];isrc:string|null};error_codes:string[];resolution?:unknown;created_entity_ids?:unknown};
type ImportState={session:{id:string;source_filename:string;status:string;row_count:number};rows:ImportRow[]}|null;

const releaseLabels:Record<string,string>={SINGLE:"Single",EP:"EP",ALBUM:"Álbum"};
const versionLabels:Record<string,string>={ORIGINAL:"Original",REMIX:"Remix",ACOUSTIC:"Acústica",LIVE:"Ao vivo",SPED_UP:"Acelerada",SLOWED:"Desacelerada",CLEAN:"Clean",EXTENDED:"Estendida",RADIO_EDIT:"Edição de rádio",OTHER:"Outra"};
const classLabels:Record<string,string>={NEW:"Novo",EXISTING:"Existente",POSSIBLE_DUPLICATE:"Possível duplicado",INVALID:"Inválido"};
const errorLabels:Record<string,string>={TRACK_TITLE_REQUIRED:"Música obrigatória",RELEASE_TYPE_INVALID:"Tipo de lançamento inválido",PRIMARY_ARTIST_REQUIRED:"Artista principal obrigatório",RELEASE_TITLE_REQUIRED:"Nome do lançamento obrigatório",TRACK_NUMBER_REQUIRED:"Número da faixa obrigatório",DURATION_INVALID:"Duração inválida",ISRC_INVALID:"ISRC inválido",LANGUAGE_INVALID:"Idioma inválido",GENRE_INVALID:"Gênero inválido",URL_INVALID:"URL inválida",ISRC_CONFLICT:"ISRC conflitante",RELEASE_DATE_INVALID:"Data inválida",EXPLICIT_INVALID:"Valor de explícita inválido"};

async function jsonApi(url:string,init?:RequestInit){
  const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}});
  const payload=await response.json();
  if(!response.ok)throw new Error(payload?.error?.message??"Não foi possível concluir a operação.");
  return payload;
}
function durationText(ms:number|null){if(ms==null)return"—";const total=Math.floor(ms/1000);return `${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`;}
function parseDuration(value:string){const m=value.trim().match(/^(\d+):(\d{2})$/);if(!m||Number(m[2])>59)return null;return(Number(m[1])*60+Number(m[2]))*1000;}

export function MusicCatalogPanel({workspaceId,artists,catalog,taxonomies,referenceData,media}:{workspaceId:string;artists:Artist[];catalog:CatalogListing;taxonomies:Taxonomy[];referenceData:Pick<ReferenceDataBundle,"languages"|"countries">;media:Media[]}){
  const router=useRouter();const[message,setMessage]=useState("");const[importState,setImportState]=useState<ImportState>(null);const[importBusy,setImportBusy]=useState(false);const[catalogState,setCatalogState]=useState(catalog);
  const genres=taxonomies.find(t=>t.code==="MUSIC_GENRE")?.values.filter(v=>v.status==="ACTIVE")??[];
  const rootGenres=genres.filter(g=>!g.parentId);const images=media.filter(m=>m.mediaKind==="IMAGE"&&m.status==="READY");const audios=media.filter(m=>m.mediaKind==="AUDIO"&&m.status==="READY");
  async function refreshCatalog(){const current=await jsonApi(`/api/workspaces/${workspaceId}/music-catalog`);setCatalogState(current);}
  async function run(url:string,body:unknown,success:string){try{await jsonApi(url,{method:"POST",body:JSON.stringify(body)});await refreshCatalog();setMessage(success);}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível concluir a operação.");}}
  async function createArtist(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await jsonApi(`/api/workspaces/${workspaceId}/artists`,{method:"POST",body:JSON.stringify({artisticName:String(d.get("artisticName")??""),civilName:String(d.get("civilName")??"")||null,bio:String(d.get("bio")??"")||null,countryCode:String(d.get("countryCode")??"")||null,languageCode:String(d.get("languageCode")??"")||null,avatarMediaAssetId:String(d.get("avatarMediaAssetId")??"")||null})});f.reset();setMessage("Artista criado.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível criar o artista.");}}
  async function updateArtistAction(artist:Artist,e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{await jsonApi(`/api/workspaces/${workspaceId}/artists/${artist.id}`,{method:"PUT",body:JSON.stringify({artisticName:String(d.get("artisticName")),civilName:String(d.get("civilName"))||null,bio:String(d.get("bio"))||null,countryCode:String(d.get("countryCode"))||null,languageCode:String(d.get("languageCode"))||null,avatarMediaAssetId:String(d.get("avatarMediaAssetId"))||null,status:String(d.get("status"))})});setMessage("Artista atualizado.");router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível atualizar o artista.");}}
  async function editTrackAction(track:Track,e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),duration=parseDuration(String(d.get("duration")??""));try{await jsonApi(`/api/workspaces/${workspaceId}/tracks/${track.id}`,{method:"PUT",body:JSON.stringify({title:String(d.get("title")),trackNumber:Number(d.get("trackNumber")),version:String(d.get("version")),durationMs:duration,isrc:String(d.get("isrc"))||null,explicitContent:d.get("explicitContent")===""?null:d.get("explicitContent")==="true",audioMediaAssetId:String(d.get("audioMediaAssetId"))||null,notes:String(d.get("notes"))||null})});await refreshCatalog();setMessage("Música atualizada.");}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível atualizar a música.");}}
  async function createRelease(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await jsonApi(`/api/workspaces/${workspaceId}/releases`,{method:"POST",body:JSON.stringify({primaryArtistId:String(d.get("primaryArtistId")),title:String(d.get("title")),type:String(d.get("type")),releaseDate:String(d.get("releaseDate"))||null,languageCode:String(d.get("languageCode"))||null,genreTaxonomyValueId:String(d.get("genreTaxonomyValueId"))||null,artworkMediaAssetId:String(d.get("artworkMediaAssetId"))||null})});f.reset();await refreshCatalog();setMessage("Lançamento criado.");}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível criar o lançamento.");}}
  async function createTrack(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),duration=parseDuration(String(d.get("duration")??""));try{await jsonApi(`/api/workspaces/${workspaceId}/tracks`,{method:"POST",body:JSON.stringify({releaseId:String(d.get("releaseId")),title:String(d.get("title")),trackNumber:Number(d.get("trackNumber")),primaryArtistIds:[String(d.get("primaryArtistId"))],featuredArtistIds:String(d.get("featuredArtistId")??"")?[String(d.get("featuredArtistId"))]:[],languageCode:String(d.get("languageCode"))||null,genreTaxonomyValueId:String(d.get("genreTaxonomyValueId"))||null,explicitContent:d.get("explicitContent")===""?null:d.get("explicitContent")==="true",version:String(d.get("version")),durationMs:duration,isrc:String(d.get("isrc"))||null,audioMediaAssetId:String(d.get("audioMediaAssetId"))||null,notes:String(d.get("notes"))||null})});f.reset();await refreshCatalog();setMessage("Música criada.");}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível criar a música.");}}
  async function createSegment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),start=parseDuration(String(d.get("start"))),end=parseDuration(String(d.get("end")));if(start==null||end==null){setMessage("Informe início e fim em Min:Seg.");return;}await run(`/api/workspaces/${workspaceId}/segments`,{trackId:String(d.get("trackId")),startMs:start,endMs:end,label:String(d.get("label"))||null,recommended:d.get("recommended")==="on",authorized:d.get("authorized")==="on"},"Trecho adicionado.");f.reset();}
  async function previewImport(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);setImportBusy(true);try{const response=await fetch(`/api/workspaces/${workspaceId}/music-import/preview`,{method:"POST",body:d});const payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message??"Não foi possível validar a planilha.");setImportState(payload);setMessage("Prévia da importação gerada.");}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível validar a planilha.");}finally{setImportBusy(false);}}
  async function resolveRow(row:ImportRow,e:FormEvent<HTMLFormElement>){e.preventDefault();if(!importState)return;const d=new FormData(e.currentTarget);const resolutions:Record<string,string>={};for(const artist of [...row.normalized_data.primaryArtists,...row.normalized_data.featuredArtists])if(artist.kind==="POSSIBLE_DUPLICATE")resolutions[artist.normalizedName]=String(d.get(artist.normalizedName)??"");try{const payload=await jsonApi(`/api/workspaces/${workspaceId}/music-import/${importState.session.id}/resolve`,{method:"POST",body:JSON.stringify({rowId:row.id,artistResolutions:resolutions})});setImportState(payload);setMessage("Duplicidade resolvida.");}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível resolver a linha.");}}
  async function confirmImport(){if(!importState)return;try{const payload=await jsonApi(`/api/workspaces/${workspaceId}/music-import/${importState.session.id}/confirm`,{method:"POST",body:"{}"});setImportState(payload);await refreshCatalog();setMessage("Importação concluída.");}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível confirmar a importação.");}}
  return <div className="module-surface catalog-shell"><header className="page-header"><div><p className="eyebrow">CATÁLOGO MUSICAL</p><h1>Catálogo musical</h1><p>Artistas, lançamentos e músicas para operações de Creator Marketing.</p></div></header>{message?<p className="notice" role="status">{message}</p>:null}
  <section id="artists" className="catalog-grid">
    <article className="card"><p className="eyebrow">ARTISTAS</p><h2>Artistas</h2>{artists.length===0?<p>Nenhum artista acessível neste workspace.</p>:<div className="stack">{artists.map(a=><div className="catalog-row" key={a.id}><strong>{a.artisticName}</strong><span>{a.civilName||"Nome civil não informado"} · {a.accessLevel==="MANAGE"?"Gerenciar":"Visualizar"}</span>{a.accessLevel==="MANAGE"?<details><summary>Editar artista</summary><form className="form compact-form" onSubmit={e=>void updateArtistAction(a,e)}><label>Nome artístico<input name="artisticName" defaultValue={a.artisticName} required/></label><label>Nome civil<input name="civilName" defaultValue={a.civilName??""}/></label><label>Situação<select name="status" defaultValue={a.status}><option value="DRAFT">Rascunho</option><option value="ACTIVE">Ativo</option><option value="ARCHIVED">Arquivado</option></select></label><label>Bio<textarea name="bio" defaultValue={a.bio??""}/></label><button type="submit">Salvar artista</button></form></details>:null}</div>)}</div>}<form className="form" onSubmit={createArtist}><label>Nome artístico<input name="artisticName" required maxLength={160}/></label><label>Nome civil<input name="civilName" maxLength={160}/></label><label>País<select name="countryCode" defaultValue=""><option value="">Não informado</option>{referenceData.countries.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Idioma<select name="languageCode" defaultValue=""><option value="">Não informado</option>{referenceData.languages.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Imagem do artista<select name="avatarMediaAssetId" defaultValue=""><option value="">Sem imagem</option>{images.map(x=><option key={x.id} value={x.id}>{x.originalFileName}</option>)}</select></label><label>Bio<textarea name="bio" rows={3}/></label><button type="submit">Criar artista</button></form></article>
    <article className="card"><p className="eyebrow">LANÇAMENTOS</p><h2>Lançamentos</h2>{catalogState.releases.length===0?<p>Nenhum lançamento cadastrado.</p>:<div className="stack">{catalogState.releases.map(r=><div className="catalog-row" key={r.id}><strong>{r.title}</strong><span>{releaseLabels[r.type]??r.type} · {r.artistic_name}</span></div>)}</div>}<form className="form" onSubmit={createRelease}><label>Artista principal<select name="primaryArtistId" required defaultValue=""><option value="" disabled>Selecione</option>{artists.filter(a=>a.accessLevel==="MANAGE").map(a=><option key={a.id} value={a.id}>{a.artisticName}</option>)}</select></label><label>Nome do lançamento<input name="title" required/></label><label>Tipo<select name="type" defaultValue="SINGLE"><option value="SINGLE">Single</option><option value="EP">EP</option><option value="ALBUM">Álbum</option></select></label><label>Data de lançamento<input name="releaseDate" type="date"/></label><label>Idioma<select name="languageCode" defaultValue=""><option value="">Não informado</option>{referenceData.languages.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Gênero<select name="genreTaxonomyValueId" defaultValue=""><option value="">Não informado</option>{rootGenres.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Arte do lançamento<select name="artworkMediaAssetId" defaultValue=""><option value="">Sem arte</option>{images.map(x=><option key={x.id} value={x.id}>{x.originalFileName}</option>)}</select></label><button type="submit">Criar lançamento</button></form></article>
    <article className="card catalog-span"><p className="eyebrow">MÚSICAS</p><h2>Músicas</h2>{catalogState.tracks.length===0?<p>Nenhuma música cadastrada.</p>:<div className="table-scroll" tabIndex={0} role="region" aria-label="Tabela de músicas"><table><thead><tr><th>Música</th><th>Lançamento</th><th>Faixa</th><th>Versão</th><th>Duração</th><th>ISRC</th></tr></thead><tbody>{catalogState.tracks.map(t=><tr key={t.id}><td><strong>{t.title}</strong><details><summary>Editar música</summary><form className="form compact-form" onSubmit={e=>void editTrackAction(t,e)}><label>Título<input name="title" defaultValue={t.title} required/></label><label>Número da faixa<input name="trackNumber" type="number" min={1} defaultValue={t.track_number}/></label><label>Versão<select name="version" defaultValue={t.version}>{Object.entries(versionLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Duração (Min:Seg)<input name="duration" defaultValue={t.duration_ms==null?"":durationText(t.duration_ms)}/></label><label>ISRC<input name="isrc" defaultValue={t.isrc??""}/></label><label>Explícita<select name="explicitContent" defaultValue={t.explicit_content==null?"":String(t.explicit_content)}><option value="">Não informado</option><option value="true">Sim</option><option value="false">Não</option></select></label><label>Áudio privado<select name="audioMediaAssetId" defaultValue={t.audio_media_asset_id??""}><option value="">Sem áudio</option>{audios.map(x=><option key={x.id} value={x.id}>{x.originalFileName}</option>)}</select></label><button type="submit">Salvar música</button></form></details></td><td>{catalogState.releases.find(r=>r.id===t.release_id)?.title??"—"}</td><td>{t.track_number}</td><td>{versionLabels[t.version]??t.version}</td><td>{durationText(t.duration_ms)}</td><td>{t.isrc??"—"}</td></tr>)}</tbody></table></div>}
    <form className="form two-column-form" onSubmit={createTrack}><label>Lançamento<select name="releaseId" required defaultValue=""><option value="" disabled>Selecione</option>{catalogState.releases.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Música<input name="title" required/></label><label>Número da faixa<input name="trackNumber" type="number" min={1} defaultValue={1} required/></label><label>Artista principal<select name="primaryArtistId" required defaultValue=""><option value="" disabled>Selecione</option>{artists.map(a=><option key={a.id} value={a.id}>{a.artisticName}</option>)}</select></label><label>Participação / Feat<select name="featuredArtistId" defaultValue=""><option value="">Nenhuma</option>{artists.map(a=><option key={a.id} value={a.id}>{a.artisticName}</option>)}</select></label><label>Versão<select name="version" defaultValue="ORIGINAL">{Object.entries(versionLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Duração (Min:Seg)<input name="duration" placeholder="3:24" pattern="\d+:\d{2}"/></label><label>ISRC<input name="isrc" placeholder="BRABC2600001"/></label><label>Idioma<select name="languageCode" defaultValue=""><option value="">Não informado</option>{referenceData.languages.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Gênero<select name="genreTaxonomyValueId" defaultValue=""><option value="">Não informado</option>{rootGenres.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Explícita<select name="explicitContent" defaultValue=""><option value="">Não informado</option><option value="true">Sim</option><option value="false">Não</option></select></label><label>Áudio privado<select name="audioMediaAssetId" defaultValue=""><option value="">Sem áudio</option>{audios.map(x=><option key={x.id} value={x.id}>{x.originalFileName}</option>)}</select></label><label className="full-field">Observações<textarea name="notes" rows={2}/></label><button type="submit">Criar música</button></form></article>
    <article className="card"><p className="eyebrow">TRECHOS</p><h2>Trechos</h2>{catalogState.segments.length===0?<p>Nenhum trecho cadastrado.</p>:<div className="stack">{catalogState.segments.map(s=><div className="catalog-row" key={s.id}><strong>{s.label||"Trecho"}</strong><span>{durationText(s.start_ms)}–{durationText(s.end_ms)} · {s.recommended?"Recomendado":"Não recomendado"} · {s.authorized?"Autorizado":"Não autorizado"}</span></div>)}</div>}<form className="form" onSubmit={createSegment}><label>Música<select name="trackId" required defaultValue=""><option value="" disabled>Selecione</option>{catalogState.tracks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>Início (Min:Seg)<input name="start" required placeholder="0:15"/></label><label>Fim (Min:Seg)<input name="end" required placeholder="0:30"/></label><label>Rótulo<input name="label" maxLength={160}/></label><label className="checkbox-field"><input name="recommended" type="checkbox"/> Recomendado</label><label className="checkbox-field"><input name="authorized" type="checkbox"/> Autorizado para uso</label><button type="submit">Adicionar trecho</button></form></article>
    <article className="card catalog-span"><div className="section-heading"><div><p className="eyebrow">IMPORTAÇÃO XLSX</p><h2>Importar catálogo</h2></div><a className="link-button" href="/api/music-catalog/template">Baixar modelo XLSX</a></div><p>Uma planilha, uma linha por música. A importação só grava após prévia, resolução e confirmação explícita.</p><form className="form" onSubmit={previewImport}><label>Planilha XLSX<input name="file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required/></label><button type="submit" disabled={importBusy}>{importBusy?"Validando…":"Gerar prévia"}</button></form>
    {importState?<><p><strong>Arquivo:</strong> {importState.session.source_filename} · <strong>Situação:</strong> {importState.session.status==="READY"?"Pronto para importar":importState.session.status==="IMPORTED"?"Importado":"Requer resolução"}</p><div className="table-scroll" tabIndex={0} role="region" aria-label="Prévia da importação"><table><thead><tr><th>Linha</th><th>Música</th><th>Lançamento</th><th>Tipo</th><th>Artistas</th><th>Classificação</th><th>Erros / resolução</th></tr></thead><tbody>{importState.rows.map(row=><tr key={row.id}><td>{row.row_number}</td><td>{row.normalized_data.trackTitle}</td><td>{row.normalized_data.releaseTitle}</td><td>{releaseLabels[row.normalized_data.releaseType]??row.normalized_data.releaseType}</td><td>{row.normalized_data.primaryArtists.map(a=>a.name).join("; ")}</td><td>{classLabels[row.classification]??row.classification}</td><td>{row.classification==="POSSIBLE_DUPLICATE"?<form className="resolution-form" onSubmit={e=>void resolveRow(row,e)}>{[...row.normalized_data.primaryArtists,...row.normalized_data.featuredArtists].filter(a=>a.kind==="POSSIBLE_DUPLICATE").map(a=><label key={a.normalizedName}>{a.name}<select name={a.normalizedName} required defaultValue=""><option value="" disabled>Resolver</option>{a.candidates?.map(c=><option key={c.id} value={c.id}>Usar {c.artisticName}</option>)}<option value="CREATE_NEW">Criar novo Artista</option></select></label>)}<button type="submit">Resolver linha</button></form>:row.error_codes?.length?row.error_codes.map(c=>errorLabels[c]??"Erro de validação").join(", "):"—"}</td></tr>)}</tbody></table></div><button type="button" onClick={()=>void confirmImport()} disabled={importState.session.status!=="READY"}>Confirmar importação</button></>:null}</article>
  </section></div>;
}
