import type{Sql,TransactionSql}from"postgres";import{authorizeWorkspacePermission}from"@/server/authorization/authorization-service";import{DomainError}from"@/server/shared/domain-error";import type{PermissionCode}from"@/server/authorization/permissions";import type{CommercialPromotedObjectType,PromotedObjectType}from"./types";
type Q=Sql|TransactionSql;const tables:Record<CommercialPromotedObjectType,string>={COMPANY:"companies",BRAND:"brands",PRODUCT:"products",SERVICE:"services",PLATFORM:"promoted_platforms",EVENT:"promoted_events",PROJECT:"promoted_projects",INSTITUTIONAL_INITIATIVE:"institutional_initiatives"};
export async function assertCommercialEntityExists(sql:Q,type:CommercialPromotedObjectType,id:string){const r=await sql.unsafe(`select id::text,status::text from ${tables[type]} where id=$1::uuid`,[id]);if(!r[0])throw new DomainError("PROMOTED_ENTITY_NOT_FOUND","Promoted entity not found",404);return r[0] as Record<string,unknown>;}
export async function authorizePromotedEntityAccess(sql:Q,input:{userId:string;workspaceId:string;entityType:PromotedObjectType;entityId:string;permission:PermissionCode;requireOwner?:boolean}){await authorizeWorkspacePermission(sql,{userId:input.userId,workspaceId:input.workspaceId,permission:input.permission});const r=await sql.unsafe("select access_level::text,status::text,expires_at from workspace_promoted_entity_access where workspace_id=$1::uuid and entity_type=$2::promoted_object_type and entity_id=$3::uuid",[input.workspaceId,input.entityType,input.entityId]);const row=r[0] as Record<string,unknown>|undefined;if(!row||row.status!=="ACTIVE"||(row.expires_at&&new Date(String(row.expires_at)).getTime()<=Date.now())||(input.requireOwner&&row.access_level!=="OWNER"))throw new DomainError("PROMOTED_ENTITY_ACCESS_DENIED","Promoted entity access denied",403);return{accessLevel:String(row.access_level)};}
export async function grantWorkspacePromotedEntityAccess(sql:Sql,input:{userId:string;workspaceId:string;targetWorkspaceId?:string;entityType:CommercialPromotedObjectType;entityId:string;accessLevel:"OWNER"|"MANAGE_CAMPAIGNS"|"VIEW"|"CAMPAIGN_ONLY";expiresAt?:Date|null}){await authorizeWorkspacePermission(sql,{userId:input.userId,workspaceId:input.workspaceId,permission:"promoted_entity.access.manage"});await assertCommercialEntityExists(sql,input.entityType,input.entityId);await authorizePromotedEntityAccess(sql,{userId:input.userId,workspaceId:input.workspaceId,entityType:input.entityType,entityId:input.entityId,permission:"promoted_entity.access.manage",requireOwner:true});const target=input.targetWorkspaceId??input.workspaceId;
  const workspace=await sql.unsafe("select 1 from workspaces where id=$1::uuid",[target]);if(!workspace[0])throw new DomainError("WORKSPACE_NOT_FOUND","Workspace not found",404);
  // An OWNER access row can only be re-granted as OWNER: no silent downgrade of a co-owner and no self lock-out.
  const current=await sql.unsafe("select access_level::text from workspace_promoted_entity_access where workspace_id=$1::uuid and entity_type=$2::promoted_object_type and entity_id=$3::uuid",[target,input.entityType,input.entityId]);
  if(current[0]?.access_level==="OWNER"&&input.accessLevel!=="OWNER")throw new DomainError("PROMOTED_ENTITY_OWNER_ACCESS_PROTECTED","Owner access cannot be downgraded by a grant",409);
  await sql.unsafe("insert into workspace_promoted_entity_access(workspace_id,entity_type,entity_id,access_level,status,expires_at,granted_by_user_id) values($1::uuid,$2::promoted_object_type,$3::uuid,$4::promoted_entity_access_level,'ACTIVE',$5::timestamptz,$6) on conflict(workspace_id,entity_type,entity_id) do update set access_level=excluded.access_level,status='ACTIVE',expires_at=excluded.expires_at,granted_by_user_id=excluded.granted_by_user_id,updated_at=now()",[target,input.entityType,input.entityId,input.accessLevel,input.expiresAt?input.expiresAt.toISOString():null,input.userId]);await sql.unsafe("insert into audit_logs(actor_type,actor_id,workspace_id,action,entity_type,entity_id,delta,origin) values('USER',$1,$2::uuid,'promoted_entity.access.granted',$3,$4,$5::jsonb,'API')",[input.userId,input.workspaceId,input.entityType.toLowerCase(),input.entityId,JSON.stringify({targetWorkspaceId:target,accessLevel:input.accessLevel,expiresAt:input.expiresAt??null})]);return{entityType:input.entityType,entityId:input.entityId,targetWorkspaceId:target,accessLevel:input.accessLevel,status:"ACTIVE" as const};}
export async function setPromotedEntityAccessStatus(sql:Sql,input:{userId:string;workspaceId:string;entityType:CommercialPromotedObjectType;entityId:string;status:"SUSPENDED"|"REVOKED"}){await authorizeWorkspacePermission(sql,{userId:input.userId,workspaceId:input.workspaceId,permission:"promoted_entity.access.manage"});const r=await sql.unsafe("update workspace_promoted_entity_access set status=$4::promoted_entity_access_status,updated_at=now() where workspace_id=$1::uuid and entity_type=$2::promoted_object_type and entity_id=$3::uuid returning entity_id::text",[input.workspaceId,input.entityType,input.entityId,input.status]);if(!r[0])throw new DomainError("PROMOTED_ENTITY_ACCESS_DENIED","Access not found",404);await sql.unsafe("insert into audit_logs(actor_type,actor_id,workspace_id,action,entity_type,entity_id,delta,origin) values(\'USER\',$1,$2::uuid,\'promoted_entity.access.status_changed\',$3,$4,$5::jsonb,\'API\')",[input.userId,input.workspaceId,input.entityType.toLowerCase(),input.entityId,JSON.stringify({status:input.status})]);return{...input};}
