import type{Sql,TransactionSql}from"postgres";import{authorizeWorkspacePermission}from"@/server/authorization/authorization-service";import{DomainError}from"@/server/shared/domain-error";import{authorizePromotedEntityAccess,assertCommercialEntityExists}from"./access";import type{CommercialPromotedObjectType}from"./types";import{assertCommercialMedia,assertReference,assertTaxonomy,normalizeCommercialText,validateHttpsUrl}from"./validation";
type Q=Sql|TransactionSql;const tables:Record<CommercialPromotedObjectType,string>={COMPANY:"companies",BRAND:"brands",PRODUCT:"products",SERVICE:"services",PLATFORM:"promoted_platforms",EVENT:"promoted_events",PROJECT:"promoted_projects",INSTITUTIONAL_INITIATIVE:"institutional_initiatives"};
async function owner(tx:Q,u:string,w:string,t:CommercialPromotedObjectType,id:string){await tx.unsafe("insert into workspace_promoted_entity_access(workspace_id,entity_type,entity_id,access_level,status,granted_by_user_id) values($1::uuid,$2::promoted_object_type,$3::uuid,'OWNER','ACTIVE',$4)",[w,t,id,u]);}
async function parent(sql:Q,u:string,w:string,t:"COMPANY"|"BRAND",id?:string|null){if(!id)return;await authorizePromotedEntityAccess(sql,{userId:u,workspaceId:w,entityType:t,entityId:id,permission:"promoted_entity.view"});}
async function dup(sql:Q,t:CommercialPromotedObjectType,n:string,confirm?:boolean){const table=tables[t],col=t==="COMPANY"?"normalized_trade_name":"normalized_name";const r=await sql.unsafe(`select id::text from ${table} where ${col}=$1 limit 5`,[n]);if(r.length&&!confirm)throw new DomainError("POSSIBLE_DUPLICATE_REQUIRES_RESOLUTION","Possible duplicate",409);return r.length?"POSSIBLE_DUPLICATE":"NEW";}
async function created(tx:Q,input:{u:string;w:string;t:CommercialPromotedObjectType;id:string;classification:string}){await owner(tx,input.u,input.w,input.t,input.id);await tx.unsafe("insert into audit_logs(actor_type,actor_id,workspace_id,action,entity_type,entity_id,delta,origin) values('USER',$1,$2::uuid,$3,$4,$5,$6::jsonb,'API')",[input.u,input.w,`${input.t.toLowerCase()}.created`,input.t.toLowerCase(),input.id,JSON.stringify({duplicateClassification:input.classification})]);}
export async function listWorkspacePromotedEntities(sql:Sql,i:{userId:string;workspaceId:string}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.view"});const out:Record<string,unknown[]>={};for(const[t,table]of Object.entries(tables)){const name=t==="COMPANY"?"trade_name":"name";const extra=t==="COMPANY"?",e.verification_status::text verification_status":"";out[t]=await sql.unsafe(`select e.id::text,e.${name} name,e.status::text,a.access_level::text,a.status::text access_status,a.expires_at${extra} from workspace_promoted_entity_access a join ${table} e on e.id=a.entity_id where a.workspace_id=$1::uuid and a.entity_type=$2::promoted_object_type and a.status=\'ACTIVE\' and (a.expires_at is null or a.expires_at>now()) order by e.${name}`,[i.workspaceId,t]);}return out;}
export async function createCompany(sql:Sql,i:{userId:string;workspaceId:string;tradeName:string;legalName?:string|null;description?:string|null;website?:string|null;countryCode?:string|null;languageCode?:string|null;logoMediaAssetId?:string|null;confirmDuplicate?:boolean}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.create"});await assertReference(sql,"reference_countries",i.countryCode);await assertReference(sql,"reference_languages",i.languageCode);await assertCommercialMedia(sql,i.workspaceId,i.logoMediaAssetId);const name=i.tradeName.trim(),n=normalizeCommercialText(name),classification=await dup(sql,"COMPANY",n,i.confirmDuplicate);const website=validateHttpsUrl(i.website);return sql.begin(async tx=>{const r=await tx.unsafe("insert into companies(legal_name,trade_name,normalized_trade_name,description,website,country_code,language_code,logo_media_asset_id) values($1,$2,$3,$4,$5,$6,$7,$8::uuid) returning id::text,trade_name name,status::text,verification_status::text",[i.legalName?.trim()||null,name,n,i.description?.trim()||null,website,i.countryCode||null,i.languageCode||null,i.logoMediaAssetId||null]);const row=r[0] as unknown as Record<string,unknown>;const id=String(row.id);await created(tx,{u:i.userId,w:i.workspaceId,t:"COMPANY",id,classification});return{...row,duplicateClassification:classification} as {id:string;name:string;status:string;verification_status:string;duplicateClassification:string};});}
export async function createBrand(sql:Sql,i:{userId:string;workspaceId:string;name:string;companyId?:string|null;description?:string|null;website?:string|null;logoMediaAssetId?:string|null;confirmDuplicate?:boolean}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.create"});await parent(sql,i.userId,i.workspaceId,"COMPANY",i.companyId);await assertCommercialMedia(sql,i.workspaceId,i.logoMediaAssetId);const name=i.name.trim(),n=normalizeCommercialText(name),classification=await dup(sql,"BRAND",n,i.confirmDuplicate);return sql.begin(async tx=>{const r=await tx.unsafe("insert into brands(company_id,name,normalized_name,description,website,logo_media_asset_id) values($1::uuid,$2,$3,$4,$5,$6::uuid) returning id::text,name,status::text",[i.companyId||null,name,n,i.description?.trim()||null,validateHttpsUrl(i.website),i.logoMediaAssetId||null]);const id=String(r[0].id);await created(tx,{u:i.userId,w:i.workspaceId,t:"BRAND",id,classification});return r[0];});}
export async function createProduct(sql:Sql,i:{userId:string;workspaceId:string;name:string;brandId?:string|null;companyId?:string|null;description?:string|null;categoryTaxonomyValueId:string;website?:string|null;primaryMediaAssetId?:string|null;confirmDuplicate?:boolean}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.create"});if(!i.brandId&&!i.companyId)throw new DomainError("PARENT_ENTITY_INVALID","Product requires parent",400);await parent(sql,i.userId,i.workspaceId,"COMPANY",i.companyId);await parent(sql,i.userId,i.workspaceId,"BRAND",i.brandId);if(i.brandId&&i.companyId){const b=await sql.unsafe("select company_id::text from brands where id=$1::uuid",[i.brandId]);if(!b[0]||String(b[0].company_id??"")!==i.companyId)throw new DomainError("PARENT_ENTITY_INVALID","Parent conflict",409);}await assertTaxonomy(sql,"PRODUCT_CATEGORY",i.categoryTaxonomyValueId);await assertCommercialMedia(sql,i.workspaceId,i.primaryMediaAssetId);const name=i.name.trim(),n=normalizeCommercialText(name),classification=await dup(sql,"PRODUCT",n,i.confirmDuplicate);return sql.begin(async tx=>{const r=await tx.unsafe("insert into products(brand_id,company_id,name,normalized_name,description,category_taxonomy_value_id,website,primary_media_asset_id) values($1::uuid,$2::uuid,$3,$4,$5,$6::uuid,$7,$8::uuid) returning id::text,name,status::text",[i.brandId||null,i.companyId||null,name,n,i.description?.trim()||null,i.categoryTaxonomyValueId,validateHttpsUrl(i.website),i.primaryMediaAssetId||null]);const id=String(r[0].id);await created(tx,{u:i.userId,w:i.workspaceId,t:"PRODUCT",id,classification});return r[0];});}
export async function createService(sql:Sql,i:{userId:string;workspaceId:string;companyId:string;name:string;description?:string|null;categoryTaxonomyValueId:string;website?:string|null;primaryMediaAssetId?:string|null;confirmDuplicate?:boolean}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.create"});if(!i.companyId)throw new DomainError("COMPANY_REQUIRED","Company required",400);await parent(sql,i.userId,i.workspaceId,"COMPANY",i.companyId);await assertTaxonomy(sql,"SERVICE_CATEGORY",i.categoryTaxonomyValueId);await assertCommercialMedia(sql,i.workspaceId,i.primaryMediaAssetId);const name=i.name.trim(),n=normalizeCommercialText(name),classification=await dup(sql,"SERVICE",n,i.confirmDuplicate);return sql.begin(async tx=>{const r=await tx.unsafe("insert into services(company_id,name,normalized_name,description,category_taxonomy_value_id,website,primary_media_asset_id) values($1::uuid,$2,$3,$4,$5::uuid,$6,$7::uuid) returning id::text,name,status::text",[i.companyId,name,n,i.description?.trim()||null,i.categoryTaxonomyValueId,validateHttpsUrl(i.website),i.primaryMediaAssetId||null]);const id=String(r[0].id);await created(tx,{u:i.userId,w:i.workspaceId,t:"SERVICE",id,classification});return r[0];});}
async function contextEntity(sql:Sql,i:{userId:string;workspaceId:string;type:"PLATFORM"|"PROJECT"|"INSTITUTIONAL_INITIATIVE";name:string;companyId?:string|null;brandId?:string|null;description?:string|null;website?:string|null;primaryMediaAssetId?:string|null;confirmDuplicate?:boolean;iosUrl?:string|null;androidUrl?:string|null}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.create"});await parent(sql,i.userId,i.workspaceId,"COMPANY",i.companyId);await parent(sql,i.userId,i.workspaceId,"BRAND",i.brandId);await assertCommercialMedia(sql,i.workspaceId,i.primaryMediaAssetId);const name=i.name.trim(),n=normalizeCommercialText(name),classification=await dup(sql,i.type,n,i.confirmDuplicate),table=tables[i.type];return sql.begin(async tx=>{const r=i.type==="PLATFORM"?await tx.unsafe(`insert into ${table}(company_id,brand_id,name,normalized_name,description,website,ios_url,android_url,primary_media_asset_id) values($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9::uuid) returning id::text,name,status::text`,[i.companyId||null,i.brandId||null,name,n,i.description?.trim()||null,validateHttpsUrl(i.website),validateHttpsUrl(i.iosUrl),validateHttpsUrl(i.androidUrl),i.primaryMediaAssetId||null]):await tx.unsafe(`insert into ${table}(company_id,brand_id,name,normalized_name,description,website,primary_media_asset_id) values($1::uuid,$2::uuid,$3,$4,$5,$6,$7::uuid) returning id::text,name,status::text`,[i.companyId||null,i.brandId||null,name,n,i.description?.trim()||null,validateHttpsUrl(i.website),i.primaryMediaAssetId||null]);const id=String(r[0].id);await created(tx,{u:i.userId,w:i.workspaceId,t:i.type,id,classification});return r[0];});}
export const createPromotedPlatform=(sql:Sql,i:Omit<Parameters<typeof contextEntity>[1],"type">)=>contextEntity(sql,{...i,type:"PLATFORM"});
export const createPromotedProject=(sql:Sql,i:Omit<Parameters<typeof contextEntity>[1],"type">)=>contextEntity(sql,{...i,type:"PROJECT"});
export const createInstitutionalInitiative=(sql:Sql,i:Omit<Parameters<typeof contextEntity>[1],"type">)=>contextEntity(sql,{...i,type:"INSTITUTIONAL_INITIATIVE"});
export async function createPromotedEvent(sql:Sql,i:{userId:string;workspaceId:string;name:string;companyId?:string|null;brandId?:string|null;description?:string|null;eventMode:"PHYSICAL"|"ONLINE"|"HYBRID";startsAt:Date;endsAt?:Date|null;timezoneCode:string;locationText?:string|null;onlineUrl?:string|null;primaryMediaAssetId?:string|null;confirmDuplicate?:boolean}){await authorizeWorkspacePermission(sql,{...i,permission:"promoted_entity.create"});await parent(sql,i.userId,i.workspaceId,"COMPANY",i.companyId);await parent(sql,i.userId,i.workspaceId,"BRAND",i.brandId);await assertReference(sql,"reference_timezones",i.timezoneCode);await assertCommercialMedia(sql,i.workspaceId,i.primaryMediaAssetId);if(i.endsAt&&i.endsAt<i.startsAt)throw new DomainError("INVALID_REQUEST","Invalid event dates",400);if(i.eventMode==="ONLINE"&&!i.onlineUrl)throw new DomainError("INVALID_REQUEST","Online URL required",400);if(i.eventMode==="PHYSICAL"&&!i.locationText?.trim())throw new DomainError("INVALID_REQUEST","Location required",400);const name=i.name.trim(),n=normalizeCommercialText(name),classification=await dup(sql,"EVENT",n,i.confirmDuplicate);return sql.begin(async tx=>{const r=await tx.unsafe("insert into promoted_events(company_id,brand_id,name,normalized_name,description,event_mode,starts_at,ends_at,timezone_code,location_text,online_url,primary_media_asset_id) values($1::uuid,$2::uuid,$3,$4,$5,$6::promoted_event_mode,$7,$8,$9,$10,$11,$12::uuid) returning id::text,name,event_mode::text,status::text",[i.companyId||null,i.brandId||null,name,n,i.description?.trim()||null,i.eventMode,i.startsAt,i.endsAt||null,i.timezoneCode,i.locationText?.trim()||null,validateHttpsUrl(i.onlineUrl),i.primaryMediaAssetId||null]);const id=String(r[0].id);await created(tx,{u:i.userId,w:i.workspaceId,t:"EVENT",id,classification});return r[0];});}
export async function evaluateCommercialReadiness(sql:Q,i:{workspaceId:string;entityType:CommercialPromotedObjectType;entityId:string}){const e=await assertCommercialEntityExists(sql,i.entityType,i.entityId),blockers:string[]=[],warnings:string[]=[];if(e.status==="ARCHIVED")blockers.push("ENTITY_ARCHIVED");if(e.status==="SUSPENDED")blockers.push("ENTITY_SUSPENDED");const a=await sql.unsafe("select status::text,expires_at from workspace_promoted_entity_access where workspace_id=$1::uuid and entity_type=$2::promoted_object_type and entity_id=$3::uuid",[i.workspaceId,i.entityType,i.entityId]);if(!a[0]||a[0].status!=="ACTIVE"||(a[0].expires_at&&new Date(String(a[0].expires_at)).getTime()<=Date.now()))blockers.push("WORKSPACE_ACCESS_REQUIRED");if(i.entityType==="COMPANY"){const c=await sql.unsafe("select verification_status::text from companies where id=$1::uuid",[i.entityId]);if(c[0]?.verification_status!=="VERIFIED")warnings.push("AUTHORIZATION_REQUIRED");}return{status:blockers.length?"BLOCKED":warnings.length?"READY_WITH_WARNINGS":"READY",blockers,warnings} as const;}
export async function activatePromotedEntity(sql:Sql,i:{userId:string;workspaceId:string;entityType:CommercialPromotedObjectType;entityId:string}){await authorizePromotedEntityAccess(sql,{...i,permission:"promoted_entity.manage",requireOwner:true});const r=await evaluateCommercialReadiness(sql,i);if(r.status==="BLOCKED")throw new DomainError("PROMOTED_ENTITY_NOT_READY","Not ready",409);await sql.unsafe(`update ${tables[i.entityType]} set status='ACTIVE',updated_at=now() where id=$1::uuid`,[i.entityId]);return{...i,status:"ACTIVE" as const,readiness:r};}

export async function updateCommercialEntity(sql:Sql,i:{userId:string;workspaceId:string;entityType:CommercialPromotedObjectType;entityId:string;name:string;description?:string|null;website?:string|null}){
 await authorizePromotedEntityAccess(sql,{userId:i.userId,workspaceId:i.workspaceId,entityType:i.entityType,entityId:i.entityId,permission:"promoted_entity.manage",requireOwner:true});
 const table=tables[i.entityType],nameColumn=i.entityType==="COMPANY"?"trade_name":"name",normalizedColumn=i.entityType==="COMPANY"?"normalized_trade_name":"normalized_name";
 const name=i.name.trim();if(!name)throw new DomainError("INVALID_REQUEST","Name required",400);
 const rows=await sql.unsafe(`update ${table} set ${nameColumn}=$2,${normalizedColumn}=$3,description=$4,website=$5,updated_at=now() where id=$1::uuid returning id::text,${nameColumn} as name,status::text`,[i.entityId,name,normalizeCommercialText(name),i.description?.trim()||null,validateHttpsUrl(i.website)]);
 if(!rows[0])throw new DomainError("PROMOTED_ENTITY_NOT_FOUND","Promoted entity not found",404);
 await sql.unsafe("insert into audit_logs(actor_type,actor_id,workspace_id,action,entity_type,entity_id,origin) values('USER',$1,$2::uuid,$3,$4,$5,'API')",[i.userId,i.workspaceId,`${i.entityType.toLowerCase()}.updated`,i.entityType.toLowerCase(),i.entityId]);
 return rows[0];
}
export async function setCompanyVerificationStatus(sql:Sql,i:{userId:string;workspaceId:string;companyId:string;verificationStatus:"UNVERIFIED"|"PENDING"|"VERIFIED"|"REJECTED"|"REVIEW_REQUIRED"}){
 await authorizePromotedEntityAccess(sql,{userId:i.userId,workspaceId:i.workspaceId,entityType:"COMPANY",entityId:i.companyId,permission:"promoted_entity.manage",requireOwner:true});
 const rows=await sql.unsafe("update companies set verification_status=$2::company_verification_status,updated_at=now() where id=$1::uuid returning id::text,verification_status::text",[i.companyId,i.verificationStatus]);
 if(!rows[0])throw new DomainError("PROMOTED_ENTITY_NOT_FOUND","Company not found",404);
 await sql.unsafe("insert into audit_logs(actor_type,actor_id,workspace_id,action,entity_type,entity_id,delta,origin) values('USER',$1,$2::uuid,'company.verification.changed','company',$3,$4::jsonb,'API')",[i.userId,i.workspaceId,i.companyId,JSON.stringify({verificationStatus:i.verificationStatus})]);
 return rows[0];
}
