import type{Sql}from"postgres";import{authorizeWorkspacePermission}from"@/server/authorization/authorization-service";import{DomainError}from"@/server/shared/domain-error";import{writeAudit}from"@/server/shared/audit";
export async function recordPublicationMetrics(sql:Sql,input:{userId:string;workspaceId:string;publicationId:string;views:number;reach:number;impressions:number;likes:number;comments:number;shares:number;saves:number;clicks:number;source:string}){
  await authorizeWorkspacePermission(sql,{userId:input.userId,workspaceId:input.workspaceId,permission:"analytics.manage"});
  const counters={views:input.views,reach:input.reach,impressions:input.impressions,likes:input.likes,comments:input.comments,shares:input.shares,saves:input.saves,clicks:input.clicks};
  if(Object.values(counters).some(v=>!Number.isSafeInteger(v)||v<0))throw new DomainError("METRICS_INVALID","Metric counters must be non-negative integers",400);
  const source=input.source.trim();
  if(!source)throw new DomainError("METRICS_INVALID","Metric source is required",400);
  return sql.begin(async(tx)=>{
    // The snapshot is immutable evidence but carries no actor, so the manual record is audited (routine collection would not be).
    const p=await tx.unsafe("select id from publications where id=$1::uuid and workspace_id=$2::uuid and status in ('PUBLISHED','VERIFIED') for share",[input.publicationId,input.workspaceId]);
    if(!p[0])throw new DomainError("PUBLICATION_NOT_METRIC_ELIGIBLE","Published publication required",409);
    const r=await tx.unsafe("insert into publication_metrics_snapshots(publication_id,views,reach,impressions,likes,comments,shares,saves,clicks,source) values($1::uuid,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id::text,captured_at",[input.publicationId,input.views,input.reach,input.impressions,input.likes,input.comments,input.shares,input.saves,input.clicks,source]);
    await writeAudit(tx,{actorId:input.userId,workspaceId:input.workspaceId,action:"analytics.metrics_recorded",entityType:"publication",entityId:input.publicationId,delta:{snapshotId:r[0].id,source,...counters}});
    return r[0];
  });
}
export async function campaignAnalytics(sql:Sql,input:{userId:string;workspaceId:string;campaignId:string}){await authorizeWorkspacePermission(sql,{userId:input.userId,workspaceId:input.workspaceId,permission:"analytics.view"});const c=await sql.unsafe("select id from campaigns where id=$1::uuid and workspace_id=$2::uuid",[input.campaignId,input.workspaceId]);if(!c[0])throw new DomainError("CAMPAIGN_NOT_FOUND","Campaign not found",404);const r=await sql.unsafe(`with latest as (select distinct on(m.publication_id) m.* from publication_metrics_snapshots m join publications p on p.id=m.publication_id where p.campaign_id=$1::uuid order by m.publication_id,m.captured_at desc) select count(distinct p.id)::int publications,count(distinct case when p.status='VERIFIED' then p.id end)::int verified_publications,coalesce(sum(l.views),0)::text views,coalesce(sum(l.reach),0)::text reach,coalesce(sum(l.impressions),0)::text impressions,coalesce(sum(l.likes),0)::text likes,coalesce(sum(l.comments),0)::text comments,coalesce(sum(l.shares),0)::text shares,coalesce(sum(l.saves),0)::text saves,coalesce(sum(l.clicks),0)::text clicks from publications p left join latest l on l.publication_id=p.id where p.campaign_id=$1::uuid`,[input.campaignId]);return r[0];}