import { randomUUID } from "node:crypto";
import { afterAll,beforeEach,describe,expect,it } from "vitest";
import { createTestSql,resetSecurityData } from "./test-db";
import { createWorkspace } from "@/server/workspace/workspace-service";
import { createMusicCatalogTemplateXlsx,MUSIC_IMPORT_HEADERS,parseMusicCatalogXlsx } from "@/server/music-catalog/xlsx";
import { previewMusicCatalogImport,confirmMusicCatalogImport,resolveMusicImportRow } from "@/server/music-catalog/import-service";

const sql=createTestSql();
async function user(email:string){const id=randomUUID();await sql.unsafe('insert into "user"(id,name,email,email_verified) values($1,$2,$3,true)',[id,"Import Test",email]);await sql.unsafe("insert into identity_profiles(user_id,status) values($1,'ACTIVE')",[id]);return id;}
async function setup(email="import@test"){const userId=await user(email);const w=await createWorkspace(sql,{userId,name:"Import",type:"LABEL",idempotencyKey:email});return{userId,workspaceId:String(w.id)};}

function crcTable(){return Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});}
const table=crcTable();function crc32(bytes:Buffer){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}function u16(n:number){const b=Buffer.alloc(2);b.writeUInt16LE(n);return b;}function u32(n:number){const b=Buffer.alloc(4);b.writeUInt32LE(n>>>0);return b;}function esc(s:string){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function fixture(rows:string[][],opts:{headers?:string[];extraSheet?:boolean;formula?:boolean}={}){
 const headers=opts.headers??[...MUSIC_IMPORT_HEADERS];const all=[headers,...rows];const xmlRows=all.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>{const col=String.fromCharCode(65+ci);if(opts.formula&&ri===1&&ci===0)return `<c r="${col}${ri+1}"><f>1+1</f><v>2</v></c>`;return `<c r="${col}${ri+1}" t="inlineStr"><is><t>${esc(v??"")}</t></is></c>`;}).join("")}</row>`).join("");
 const sheets=opts.extraSheet?'<sheet name="Catálogo" sheetId="1" r:id="rId1"/><sheet name="Extra" sheetId="2" r:id="rId2"/>':'<sheet name="Catálogo" sheetId="1" r:id="rId1"/>';
 const rels=opts.extraSheet?'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>':'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>';
 const entries=[["[Content_Types].xml",'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],["_rels/.rels",'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],["xl/workbook.xml",`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets}</sheets></workbook>`],["xl/_rels/workbook.xml.rels",`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels}</Relationships>`],["xl/worksheets/sheet1.xml",`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${xmlRows}</sheetData></worksheet>`],["xl/worksheets/sheet2.xml",'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData/></worksheet>']].filter(e=>opts.extraSheet||e[0]!=="xl/worksheets/sheet2.xml") as [string,string][];
 let offset=0;const locals:Buffer[]=[];const centrals:Buffer[]=[];for(const [nameText,body] of entries){const name=Buffer.from(nameText),bytes=Buffer.from(body),crc=crc32(bytes);const local=Buffer.concat([Buffer.from([0x50,0x4b,0x03,0x04]),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(bytes.length),u32(bytes.length),u16(name.length),u16(0),name,bytes]);locals.push(local);centrals.push(Buffer.concat([Buffer.from([0x50,0x4b,0x01,0x02]),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(bytes.length),u32(bytes.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length;}const central=Buffer.concat(centrals);return Buffer.concat([...locals,central,Buffer.concat([Buffer.from([0x50,0x4b,0x05,0x06]),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(central.length),u32(offset),u16(0)])]);
}
function row(values:Partial<Record<(typeof MUSIC_IMPORT_HEADERS)[number],string>>){return MUSIC_IMPORT_HEADERS.map(h=>values[h]??"");}

describe("Music Catalog XLSX import",()=>{
 beforeEach(async()=>{await resetSecurityData(sql);});afterAll(async()=>{await sql.end();});
 it("generates exact canonical one-sheet template",()=>{expect(parseMusicCatalogXlsx(createMusicCatalogTemplateXlsx())).toEqual([]);expect(MUSIC_IMPORT_HEADERS).toHaveLength(20);});
 it("imports SINGLE with default Release title and Track 1, then confirmation is idempotent",async()=>{const x=await setup();const bytes=fixture([row({"Música":"Faixa Um","Tipo de Lançamento":"Single","Artista Principal":"Artista Novo","Idioma":"Português (Brasil)","Gênero":"Pop","Explícita":"Não","Versão":"Original","Duração":"3:20","ISRC":"BRABC2600011","Spotify":"https://open.spotify.com/track/example"})]);const p=await previewMusicCatalogImport(sql,{...x,sourceFilename:"single.xlsx",bytes});expect(p.session.status).toBe("READY");expect(p.rows[0].classification).toBe("NEW");await confirmMusicCatalogImport(sql,{...x,sessionId:String(p.session.id)});await confirmMusicCatalogImport(sql,{...x,sessionId:String(p.session.id)});const releases=await sql.unsafe("select title,type::text from releases");const tracks=await sql.unsafe("select title,track_number,isrc from tracks");expect(releases).toHaveLength(1);expect(releases[0]).toMatchObject({title:"Faixa Um",type:"SINGLE"});expect(tracks).toHaveLength(1);expect(tracks[0]).toMatchObject({title:"Faixa Um",track_number:1,isrc:"BRABC2600011"});});
 it("groups EP rows into one Release and preserves semicolon Artist credits",async()=>{const x=await setup();const rows=[row({"Música":"Um","Nome do Lançamento":"Meu EP","Tipo de Lançamento":"EP","Número da Faixa":"1","Artista Principal":"A; B","Participação / Feat":"C","Gênero":"Pop"}),row({"Música":"Dois","Nome do Lançamento":"Meu EP","Tipo de Lançamento":"EP","Número da Faixa":"2","Artista Principal":"A; B","Gênero":"Pop"})];const p=await previewMusicCatalogImport(sql,{...x,sourceFilename:"ep.xlsx",bytes:fixture(rows)});expect(p.session.status).toBe("READY");await confirmMusicCatalogImport(sql,{...x,sessionId:String(p.session.id)});expect(Number((await sql.unsafe("select count(*)::int c from releases"))[0].c)).toBe(1);expect(Number((await sql.unsafe("select count(*)::int c from tracks"))[0].c)).toBe(2);expect(Number((await sql.unsafe("select count(*)::int c from track_artist_credits where role='PRIMARY_ARTIST'"))[0].c)).toBe(4);});
 it("requires explicit resolution for possible global Artist duplicate",async()=>{const a=await setup("a@import.test");const b=await setup("b@import.test");await sql.unsafe("insert into artists(artistic_name,normalized_artistic_name) values('Nome Igual','nome igual')");const bytes=fixture([row({"Música":"Nova","Tipo de Lançamento":"Single","Artista Principal":"Nome Igual"})]);const p=await previewMusicCatalogImport(sql,{userId:a.userId,workspaceId:a.workspaceId,sourceFilename:"dup.xlsx",bytes});expect(p.session.status).toBe("RESOLUTION_REQUIRED");expect(p.rows[0].classification).toBe("POSSIBLE_DUPLICATE");await expect(confirmMusicCatalogImport(sql,{userId:a.userId,workspaceId:a.workspaceId,sessionId:String(p.session.id)})).rejects.toMatchObject({code:"MUSIC_IMPORT_DUPLICATE_RESOLUTION_REQUIRED"});const row0=p.rows[0];await resolveMusicImportRow(sql,{userId:a.userId,workspaceId:a.workspaceId,sessionId:String(p.session.id),rowId:String(row0.id),artistResolutions:{"nome igual":"CREATE_NEW"}});const done=await confirmMusicCatalogImport(sql,{userId:a.userId,workspaceId:a.workspaceId,sessionId:String(p.session.id)});expect(done.session.status).toBe("IMPORTED");expect(b.workspaceId).not.toBe(a.workspaceId);});
 it("rejects malformed workbook, extra sheet, unexpected column and excessive rows",async()=>{expect(()=>parseMusicCatalogXlsx(Buffer.from("not-xlsx"))).toThrow();expect(()=>parseMusicCatalogXlsx(fixture([], {extraSheet:true}))).toThrow();const bad:string[]=[...MUSIC_IMPORT_HEADERS];bad[0]="Faixa";expect(()=>parseMusicCatalogXlsx(fixture([],{headers:bad}))).toThrow();expect(()=>parseMusicCatalogXlsx(fixture(Array.from({length:1001},()=>row({"Música":"x","Tipo de Lançamento":"Single","Artista Principal":"A"}))))).toThrow();});
 it("treats formula cells as data and never evaluates cached result",()=>{const parsed=parseMusicCatalogXlsx(fixture([row({"Música":"ignored","Tipo de Lançamento":"Single","Artista Principal":"A"})],{formula:true}));expect(parsed[0].values["Música"]).toBe("=1+1");});
 it("rejects invalid URLs and duplicate Track numbers before inconsistent import",async()=>{const x=await setup();const invalid=await previewMusicCatalogImport(sql,{...x,sourceFilename:"bad.xlsx",bytes:fixture([row({"Música":"Bad","Tipo de Lançamento":"Single","Artista Principal":"A","Spotify":"javascript:alert(1)"})])});expect(invalid.rows[0].error_codes).toContain("URL_INVALID");const dupRows=[row({"Música":"Um","Nome do Lançamento":"Album","Tipo de Lançamento":"Álbum","Número da Faixa":"1","Artista Principal":"A"}),row({"Música":"Dois","Nome do Lançamento":"Album","Tipo de Lançamento":"Álbum","Número da Faixa":"1","Artista Principal":"A"})];const p=await previewMusicCatalogImport(sql,{...x,sourceFilename:"dup-track.xlsx",bytes:fixture(dupRows)});await expect(confirmMusicCatalogImport(sql,{...x,sessionId:String(p.session.id)})).rejects.toMatchObject({code:"MUSIC_IMPORT_INVALID"});});
});
