import type{Sql}from"postgres";import{DomainError}from"@/server/shared/domain-error";
export const normalizeAlias=(v:string)=>v.trim().toLowerCase().replace(/\s+/g," ");
export type TaxonomyValueRow={id:string;code:string;label:string;parentId:string|null;status:string;sortOrder:number};
export type TaxonomyDefinitionRow={id:string;code:string;display_name_pt_br:string;description:string;hierarchy_enabled:boolean;max_depth:number|null;status:string;values:TaxonomyValueRow[]};
export async function listTaxonomies(sql:Sql){return sql.unsafe<TaxonomyDefinitionRow[]>("select td.id::text,td.code,td.display_name_pt_br,td.description,td.hierarchy_enabled,td.max_depth,td.status::text,json_agg(json_build_object('id',tv.id::text,'code',tv.code,'label',tv.display_label_pt_br,'parentId',tv.parent_id::text,'status',tv.status::text,'sortOrder',tv.sort_order) order by tv.sort_order,tv.display_label_pt_br) filter(where tv.id is not null) as values from taxonomy_definitions td left join taxonomy_values tv on tv.taxonomy_definition_id=td.id group by td.id order by td.display_name_pt_br");}
export async function resolveTaxonomyAlias(sql:Sql,definitionCode:string,input:string){const rows=await sql.unsafe("select tv.id::text,tv.code,tv.display_label_pt_br,tv.status::text from taxonomy_values tv join taxonomy_definitions td on td.id=tv.taxonomy_definition_id left join taxonomy_aliases ta on ta.taxonomy_value_id=tv.id where td.code=$1 and (lower(tv.code)=lower($2) or lower(tv.display_label_pt_br)=lower($2) or ta.normalized_alias=$3) limit 1",[definitionCode,input,normalizeAlias(input)]);if(!rows[0])throw new DomainError("TAXONOMY_NOT_FOUND","Taxonomy value not found",404);return rows[0];}
export async function assertTaxonomyValueSelectable(sql:Sql,valueId:string){const rows=await sql.unsafe("select status::text from taxonomy_values where id=$1::uuid",[valueId]);if(!rows[0])throw new DomainError("TAXONOMY_NOT_FOUND","Taxonomy value not found",404);if((rows[0] as Record<string,unknown>).status==="DEPRECATED")throw new DomainError("TAXONOMY_VALUE_DEPRECATED","Deprecated taxonomy value cannot be selected",409);}
export async function setTaxonomyParent(sql:Sql,input:{valueId:string;parentId:string|null}){if(input.parentId===input.valueId)throw new DomainError("INVALID_TAXONOMY_HIERARCHY","Self parent rejected",409);return sql.begin(async tx=>{const v=await tx.unsafe("select taxonomy_definition_id::text from taxonomy_values where id=$1::uuid for update",[input.valueId]);if(!v[0])throw new DomainError("TAXONOMY_NOT_FOUND","Taxonomy value not found",404);const definitionId=String((v[0] as Record<string,unknown>).taxonomy_definition_id);if(input.parentId){const p=await tx.unsafe("select taxonomy_definition_id::text from taxonomy_values where id=$1::uuid",[input.parentId]);if(!p[0]||String((p[0] as Record<string,unknown>).taxonomy_definition_id)!==definitionId)throw new DomainError("INVALID_TAXONOMY_HIERARCHY","Cross taxonomy parent rejected",409);const cycle=await tx.unsafe("with recursive a as(select id,parent_id from taxonomy_values where id=$1::uuid union all select tv.id,tv.parent_id from taxonomy_values tv join a on tv.id=a.parent_id)select 1 from a where id=$2::uuid limit 1",[input.parentId,input.valueId]);if(cycle[0])throw new DomainError("INVALID_TAXONOMY_HIERARCHY","Taxonomy cycle rejected",409);const d=await tx.unsafe("select hierarchy_enabled,max_depth from taxonomy_definitions where id=$1::uuid",[definitionId]);const def=d[0] as Record<string,unknown>;if(!def.hierarchy_enabled)throw new DomainError("INVALID_TAXONOMY_HIERARCHY","Hierarchy disabled",409);const dep=await tx.unsafe("with recursive a as(select id,parent_id,1 depth from taxonomy_values where id=$1::uuid union all select tv.id,tv.parent_id,a.depth+1 from taxonomy_values tv join a on tv.id=a.parent_id)select max(depth)::int depth from a",[input.parentId]);if(Number(def.max_depth)&&Number((dep[0] as Record<string,unknown>).depth)>=Number(def.max_depth))throw new DomainError("INVALID_TAXONOMY_HIERARCHY","Taxonomy max depth exceeded",409);}await tx.unsafe("update taxonomy_values set parent_id=$2::uuid,updated_at=now() where id=$1::uuid",[input.valueId,input.parentId]);return input;});}
export async function deprecateTaxonomyValue(sql:Sql,input:{valueId:string;supersededById?:string}){await sql.unsafe("update taxonomy_values set status='DEPRECATED',superseded_by_id=$2::uuid,updated_at=now() where id=$1::uuid",[input.valueId,input.supersededById??null]);}
